### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Ahadkhan-12** [Ahadkhan-12/Stayfinder---Explore-the-world-around-you#1]
**ISSUE :** when i switch from restaurants  to hotel , sometimes hotel doesn't update in list section and map section.

**Comment by BishamKunwor** [comment]
Hello, I'm willing to help on the project but I could not replicate the issue you've mentioned. Please provide further information to recreate the issue.

**Comment by Magesh-sam** [comment]
Need more clarity to the issue

**Comment by Darshanbs2001** [comment]
I too tried to recreate the same issue but only got it once and after some time I checked for the same issue but the issue was resolved may be it is a api server problem . During my  first test in which i was able to replicate the exact issue that you specified and I inspected in the browser and found that the data returned by the api was an empty array . In the second test after refreshing the website I got it working all right and also it seems that you are using the depreciated version for the api please update the api to solve the issue may be that  might solve this  issue
 see this screen shot below i tried the api myself it gave me the same empty array:
![Screenshot 2023-04-06 105042](https://user-images.githubusercontent.com/73336457/230279038-008a32b4-91d4-447f-87c2-bc47f1cea3d9.png)
see i have attached the inspection result also of your live website:
![Screenshot 2023-04-06 105508](https://user-images.githubusercontent.com/73336457/230279683-2cf31eba-0b43-488a-a2bb-339363995680.png)

**Comment by Ahadkhan-12** [comment]
I am using depreciated version as to use other API i have to give card permission and all , Can we fix this issue , like if we find a empty array we can return a div in List.jsx which shows no data received 
@Darshanbs2001

**Comment by Ahadkhan-12** [comment]
Issue Resolved 👍 

1. Made changes so that when we receive empty array , it will tell the user that no data found in that area.
